# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'


flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'testOCtoFlutter' do
  install_all_flutter_pods(flutter_application_path)
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for testOCtoFlutter
  pod 'AFNetworking'


  target 'testOCtoFlutterTests' do
    install_all_flutter_pods(flutter_application_path)
    inherit! :search_paths
    # Pods for testing
  end

  target 'testOCtoFlutterUITests' do
    install_all_flutter_pods(flutter_application_path)
    # Pods for testing
  end

end
